server.port=3030

spring.datasource.url=jdbc:mysql://localhost:3309/librarydb2
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
